### ISSUE TITLE
Erreur dans le titre

### ISSUE THREAD

**Issue by FlorentDiabi** [Zelcor/Zelcor#1]
Il y a écrit "Bienvenu" et l'absence du "e" à la fin me fait du mal. @Zelcor

**Comment by FlorentDiabi** [comment]
Cela fait désormais 1 semaine, toujours aucune modiifcation. @Zelcor

**Comment by Zelcor** [comment]
Pour info cher collaborateur, sur mes derniers commit le problème est fix ;)
